DependsOn: ServerlessVPCGA
Type: AWS::RDS::DBInstance
Properties:
  Engine: postgres
  AllocatedStorage: 20
  PubliclyAccessible: true
  DBInstanceClass: db.t2.micro
  DBName: ${self:custom.POSTGRESQL.DBNAME}
  MasterUsername: ${self:custom.POSTGRESQL.USER}
  MasterUserPassword: ${self:custom.POSTGRESQL.PASS}
  VPCSecurityGroups:
  - !GetAtt ServerlessSecurityGroup.GroupId
  DBSubnetGroupName:
    Ref: ServerlessSubnetGroup